component: http
name: http-django-hdZCCSSMOx
inputs:
  src:
    hook: pip3 install -r requirements.txt -t ./
    dist: ./
    exclude:
      - .env
      - __pycache__/**
  region: ap-beijing
  faas:
    framework: django
    name: '${name}'
    runtime: Python3.6
    memorySize: 512
    eip: false
    timeout: 3
    tags: []
    environments: []
  apigw:
    protocols:
      - http
      - https
    timeout: 60
    environment: release
    customDomains: []
  isAutoCiDeploy: false
org: '1317428810'
app: test
stage: dev
