component: http
name: http-django-I5kLN-kFHx
org: '1317428810'
app: nwpu
stage: dev
inputs:
  region: ap-guangzhou
  src:
    hook: pip3 install -r requirements.txt -t ./
    dist: ./
    exclude:
      - .env
      - __pycache__/**
  faas:
    runtime: Python3.6
    eip: true
    timeout: 3
    memorySize: 2048
    tags: []
    framework: django
    environments:
      - key: SERVERLESS
        value: '1'
  apigw:
    timeout: 60
    protocols:
      - http
      - https
    environment: release
    customDomains: []
  isAutoCiDeploy: true
  codePlatform: GITHUB
  gitUrl: 'https://github.com/wushenhaoyu/NWPUgame_Django.git'
  branch: master
